name: Greetings

on:
  - pull_request_target
  - issues

jobs:
  greeting:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome! I noticed this is your first issue. Thank you for taking the time to help me. Please refer to CONTRIBUTING.md (if available), and feel free to submit a pull request."
        pr-message: "Thank you for your pull request! I'll review it as soon as possible. In the meantime, please take a look at the CONTRIBUTING.md file (if available). Your help is greatly appreciated."
